// This file is auto-generated by the Terminal.Gui.Elmish.Generator.
// Do not edit by hand.

namespace Terminal.Gui.Elmish

open System
open System.Collections.Generic
open Terminal.Gui.App
open Terminal.Gui.Views

[<RequireQualifiedAccess>]
module internal PKey =

  type ViewPKeys() =

    // Properties
    member val Arrangement: PropKey<Terminal.Gui.ViewBase.ViewArrangement> = PropKey.Create.simple "View.Arrangement"
    member val AssignHotKeys: PropKey<bool> = PropKey.Create.simple "View.AssignHotKeys"
    member val BorderStyle: PropKey<Terminal.Gui.Drawing.LineStyle> = PropKey.Create.simple "View.BorderStyle"
    member val CanFocus: PropKey<bool> = PropKey.Create.simple "View.CanFocus"

    member val CommandsToBubbleUp: PropKey<IReadOnlyList<Terminal.Gui.Input.Command>> =
      PropKey.Create.simple "View.CommandsToBubbleUp"

    member val ContentSizeTracksViewport: PropKey<bool> = PropKey.Create.simple "View.ContentSizeTracksViewport"
    member val Cursor: PropKey<Terminal.Gui.Drivers.Cursor> = PropKey.Create.simple "View.Cursor"
    member val Data: PropKey<System.Object> = PropKey.Create.simple "View.Data"

    member val DefaultAcceptView: PropKey<Terminal.Gui.ViewBase.View> =
      PropKey.Create.view "View.DefaultAcceptView_view"

    member val DefaultAcceptView_element: PropKey<ITerminalElement> =
      PropKey.Create.subElement "View.DefaultAcceptView_element"

    member val Enabled: PropKey<bool> = PropKey.Create.simple "View.Enabled"
    member val Frame: PropKey<System.Drawing.Rectangle> = PropKey.Create.simple "View.Frame"
    member val HasFocus: PropKey<bool> = PropKey.Create.simple "View.HasFocus"
    member val Height: PropKey<Terminal.Gui.ViewBase.Dim> = PropKey.Create.simple "View.Height"
    member val HotKey: PropKey<Terminal.Gui.Input.Key> = PropKey.Create.simple "View.HotKey"
    member val HotKeySpecifier: PropKey<System.Text.Rune> = PropKey.Create.simple "View.HotKeySpecifier"
    member val Id: PropKey<string> = PropKey.Create.simple "View.Id"
    member val IsInitialized: PropKey<bool> = PropKey.Create.simple "View.IsInitialized"

    member val MouseHighlightStates: PropKey<Terminal.Gui.ViewBase.MouseState> =
      PropKey.Create.simple "View.MouseHighlightStates"

    member val MouseHoldRepeat: PropKey<Nullable<Terminal.Gui.Input.MouseFlags>> =
      PropKey.Create.simple "View.MouseHoldRepeat"

    member val MousePositionTracking: PropKey<bool> = PropKey.Create.simple "View.MousePositionTracking"
    member val PreserveTrailingSpaces: PropKey<bool> = PropKey.Create.simple "View.PreserveTrailingSpaces"
    member val SchemeName: PropKey<string> = PropKey.Create.simple "View.SchemeName"
    member val ShadowStyle: PropKey<Terminal.Gui.ViewBase.ShadowStyle> = PropKey.Create.simple "View.ShadowStyle"
    member val SuperViewRendersLineCanvas: PropKey<bool> = PropKey.Create.simple "View.SuperViewRendersLineCanvas"
    member val TabStop: PropKey<Nullable<Terminal.Gui.ViewBase.TabBehavior>> = PropKey.Create.simple "View.TabStop"
    member val Text: PropKey<string> = PropKey.Create.simple "View.Text"
    member val TextAlignment: PropKey<Terminal.Gui.ViewBase.Alignment> = PropKey.Create.simple "View.TextAlignment"
    member val TextDirection: PropKey<Terminal.Gui.Text.TextDirection> = PropKey.Create.simple "View.TextDirection"
    member val Title: PropKey<string> = PropKey.Create.simple "View.Title"
    member val UsedHotKeys: PropKey<HashSet<Terminal.Gui.Input.Key>> = PropKey.Create.simple "View.UsedHotKeys"
    member val ValidatePosDim: PropKey<bool> = PropKey.Create.simple "View.ValidatePosDim"

    member val VerticalTextAlignment: PropKey<Terminal.Gui.ViewBase.Alignment> =
      PropKey.Create.simple "View.VerticalTextAlignment"

    member val Viewport: PropKey<System.Drawing.Rectangle> = PropKey.Create.simple "View.Viewport"

    member val ViewportSettings: PropKey<Terminal.Gui.ViewBase.ViewportSettingsFlags> =
      PropKey.Create.simple "View.ViewportSettings"

    member val Visible: PropKey<bool> = PropKey.Create.simple "View.Visible"
    member val Width: PropKey<Terminal.Gui.ViewBase.Dim> = PropKey.Create.simple "View.Width"

    // Events
    member val Accepted: PropKey<Terminal.Gui.Input.CommandEventArgs -> unit> =
      PropKey.Create.event "View.Accepted_event"

    member val Accepting: PropKey<Terminal.Gui.Input.CommandEventArgs -> unit> =
      PropKey.Create.event "View.Accepting_event"

    member val Activated: PropKey<EventArgs<Terminal.Gui.Input.ICommandContext> -> unit> =
      PropKey.Create.event "View.Activated_event"

    member val Activating: PropKey<Terminal.Gui.Input.CommandEventArgs -> unit> =
      PropKey.Create.event "View.Activating_event"

    member val AdvancingFocus: PropKey<Terminal.Gui.ViewBase.AdvanceFocusEventArgs -> unit> =
      PropKey.Create.event "View.AdvancingFocus_event"

    member val BorderStyleChanged: PropKey<System.EventArgs -> unit> =
      PropKey.Create.event "View.BorderStyleChanged_event"

    member val CanFocusChanged: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.CanFocusChanged_event"

    member val ClearedViewport: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.ClearedViewport_event"

    member val ClearingViewport: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.ClearingViewport_event"

    member val CommandNotBound: PropKey<Terminal.Gui.Input.CommandEventArgs -> unit> =
      PropKey.Create.event "View.CommandNotBound_event"

    member val ContentSizeChanged: PropKey<ValueChangedEventArgs<Nullable<System.Drawing.Size>> -> unit> =
      PropKey.Create.event "View.ContentSizeChanged_event"

    member val ContentSizeChanging: PropKey<ValueChangingEventArgs<Nullable<System.Drawing.Size>> -> unit> =
      PropKey.Create.event "View.ContentSizeChanging_event"

    member val Disposing: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.Disposing_event"

    member val DrawComplete: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.DrawComplete_event"

    member val DrawingContent: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.DrawingContent_event"

    member val DrawingSubViews: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.DrawingSubViews_event"

    member val DrawingText: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.DrawingText_event"

    member val DrewText: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.DrewText_event"
    member val EnabledChanged: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.EnabledChanged_event"

    member val FocusedChanged: PropKey<Terminal.Gui.ViewBase.HasFocusEventArgs -> unit> =
      PropKey.Create.event "View.FocusedChanged_event"

    member val FrameChanged: PropKey<EventArgs<System.Drawing.Rectangle> -> unit> =
      PropKey.Create.event "View.FrameChanged_event"

    member val GettingAttributeForRole: PropKey<Terminal.Gui.Drawing.VisualRoleEventArgs -> unit> =
      PropKey.Create.event "View.GettingAttributeForRole_event"

    member val GettingScheme: PropKey<ResultEventArgs<Terminal.Gui.Drawing.Scheme> -> unit> =
      PropKey.Create.event "View.GettingScheme_event"

    member val HandlingHotKey: PropKey<Terminal.Gui.Input.CommandEventArgs -> unit> =
      PropKey.Create.event "View.HandlingHotKey_event"

    member val HasFocusChanged: PropKey<Terminal.Gui.ViewBase.HasFocusEventArgs -> unit> =
      PropKey.Create.event "View.HasFocusChanged_event"

    member val HasFocusChanging: PropKey<Terminal.Gui.ViewBase.HasFocusEventArgs -> unit> =
      PropKey.Create.event "View.HasFocusChanging_event"

    member val HeightChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.ViewBase.Dim> -> unit> =
      PropKey.Create.event "View.HeightChanged_event"

    member val HeightChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.ViewBase.Dim> -> unit> =
      PropKey.Create.event "View.HeightChanging_event"

    member val HotKeyChanged: PropKey<Terminal.Gui.Input.KeyChangedEventArgs -> unit> =
      PropKey.Create.event "View.HotKeyChanged_event"

    member val HotKeyCommand: PropKey<EventArgs<Terminal.Gui.Input.ICommandContext> -> unit> =
      PropKey.Create.event "View.HotKeyCommand_event"

    member val Initialized: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.Initialized_event"
    member val KeyDown: PropKey<Terminal.Gui.Input.Key -> unit> = PropKey.Create.event "View.KeyDown_event"

    member val KeyDownNotHandled: PropKey<Terminal.Gui.Input.Key -> unit> =
      PropKey.Create.event "View.KeyDownNotHandled_event"

    member val KeyUp: PropKey<Terminal.Gui.Input.Key -> unit> = PropKey.Create.event "View.KeyUp_event"

    member val MouseEnter: PropKey<System.ComponentModel.CancelEventArgs -> unit> =
      PropKey.Create.event "View.MouseEnter_event"

    member val MouseEvent: PropKey<Terminal.Gui.Input.Mouse -> unit> = PropKey.Create.event "View.MouseEvent_event"

    member val MouseHoldRepeatChanged: PropKey<ValueChangedEventArgs<Nullable<Terminal.Gui.Input.MouseFlags>> -> unit> =
      PropKey.Create.event "View.MouseHoldRepeatChanged_event"

    member val MouseHoldRepeatChanging: PropKey<ValueChangingEventArgs<Nullable<Terminal.Gui.Input.MouseFlags>> -> unit> =
      PropKey.Create.event "View.MouseHoldRepeatChanging_event"

    member val MouseLeave: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.MouseLeave_event"

    member val MouseStateChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.MouseState> -> unit> =
      PropKey.Create.event "View.MouseStateChanged_event"

    member val Removed: PropKey<Terminal.Gui.ViewBase.SuperViewChangedEventArgs -> unit> =
      PropKey.Create.event "View.Removed_event"

    member val SchemeChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.Drawing.Scheme> -> unit> =
      PropKey.Create.event "View.SchemeChanged_event"

    member val SchemeChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.Drawing.Scheme> -> unit> =
      PropKey.Create.event "View.SchemeChanging_event"

    member val SchemeNameChanged: PropKey<ValueChangedEventArgs<string> -> unit> =
      PropKey.Create.event "View.SchemeNameChanged_event"

    member val SchemeNameChanging: PropKey<ValueChangingEventArgs<string> -> unit> =
      PropKey.Create.event "View.SchemeNameChanging_event"

    member val SubViewAdded: PropKey<Terminal.Gui.ViewBase.SuperViewChangedEventArgs -> unit> =
      PropKey.Create.event "View.SubViewAdded_event"

    member val SubViewLayout: PropKey<Terminal.Gui.ViewBase.LayoutEventArgs -> unit> =
      PropKey.Create.event "View.SubViewLayout_event"

    member val SubViewRemoved: PropKey<Terminal.Gui.ViewBase.SuperViewChangedEventArgs -> unit> =
      PropKey.Create.event "View.SubViewRemoved_event"

    member val SubViewsLaidOut: PropKey<Terminal.Gui.ViewBase.LayoutEventArgs -> unit> =
      PropKey.Create.event "View.SubViewsLaidOut_event"

    member val SuperViewChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.ViewBase.View> -> unit> =
      PropKey.Create.event "View.SuperViewChanged_event"

    member val SuperViewChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.ViewBase.View> -> unit> =
      PropKey.Create.event "View.SuperViewChanging_event"

    member val TextChanged: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.TextChanged_event"
    member val TitleChanged: PropKey<EventArgs<string> -> unit> = PropKey.Create.event "View.TitleChanged_event"
    member val TitleChanging: PropKey<CancelEventArgs<string> -> unit> = PropKey.Create.event "View.TitleChanging_event"

    member val ViewportChanged: PropKey<Terminal.Gui.ViewBase.DrawEventArgs -> unit> =
      PropKey.Create.event "View.ViewportChanged_event"

    member val VisibleChanged: PropKey<System.EventArgs -> unit> = PropKey.Create.event "View.VisibleChanged_event"

    member val VisibleChanging: PropKey<CancelEventArgs<bool> -> unit> =
      PropKey.Create.event "View.VisibleChanging_event"

    member val WidthChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.ViewBase.Dim> -> unit> =
      PropKey.Create.event "View.WidthChanged_event"

    member val WidthChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.ViewBase.Dim> -> unit> =
      PropKey.Create.event "View.WidthChanging_event"

  type AdornmentPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Diagnostics: PropKey<Terminal.Gui.ViewBase.ViewDiagnosticFlags> =
      PropKey.Create.simple "Adornment.Diagnostics"

    member val Parent: PropKey<Terminal.Gui.ViewBase.View> = PropKey.Create.view "Adornment.Parent_view"
    member val Parent_element: PropKey<ITerminalElement> = PropKey.Create.subElement "Adornment.Parent_element"
    member val SuperViewRendersLineCanvas: PropKey<bool> = PropKey.Create.simple "Adornment.SuperViewRendersLineCanvas"
    member val Thickness: PropKey<Terminal.Gui.Drawing.Thickness> = PropKey.Create.simple "Adornment.Thickness"
    member val Viewport: PropKey<System.Drawing.Rectangle> = PropKey.Create.simple "Adornment.Viewport"

    // Events
    member val ThicknessChanged: PropKey<System.EventArgs -> unit> =
      PropKey.Create.event "Adornment.ThicknessChanged_event"

  type AttributePickerPKeys() =
    inherit ViewPKeys()

    // Properties
    member val SampleText: PropKey<string> = PropKey.Create.simple "AttributePicker.SampleText"
    member val Value: PropKey<Nullable<Terminal.Gui.Drawing.Attribute>> = PropKey.Create.simple "AttributePicker.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<Nullable<Terminal.Gui.Drawing.Attribute>> -> unit> =
      PropKey.Create.event "AttributePicker.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "AttributePicker.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Nullable<Terminal.Gui.Drawing.Attribute>> -> unit> =
      PropKey.Create.event "AttributePicker.ValueChanging_event"

  type BarPKeys() =
    inherit ViewPKeys()

    // Properties
    member val AlignmentModes: PropKey<Terminal.Gui.ViewBase.AlignmentModes> =
      PropKey.Create.simple "Bar.AlignmentModes"

    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> = PropKey.Create.simple "Bar.Orientation"

    // Events
    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "Bar.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "Bar.OrientationChanging_event"

  type BorderPKeys() =
    inherit AdornmentPKeys()

    // Properties
    member val LineStyle: PropKey<Terminal.Gui.Drawing.LineStyle> = PropKey.Create.simple "Border.LineStyle"
    member val Settings: PropKey<Terminal.Gui.ViewBase.BorderSettings> = PropKey.Create.simple "Border.Settings"

  type ButtonPKeys() =
    inherit ViewPKeys()

    // Properties
    member val HotKeySpecifier: PropKey<System.Text.Rune> = PropKey.Create.simple "Button.HotKeySpecifier"
    member val IsDefault: PropKey<bool> = PropKey.Create.simple "Button.IsDefault"
    member val NoDecorations: PropKey<bool> = PropKey.Create.simple "Button.NoDecorations"
    member val NoPadding: PropKey<bool> = PropKey.Create.simple "Button.NoPadding"
    member val Text: PropKey<string> = PropKey.Create.simple "Button.Text"

  type CharMapPKeys() =
    inherit ViewPKeys()

    // Properties
    member val SelectedCodePoint: PropKey<int> = PropKey.Create.simple "CharMap.SelectedCodePoint"
    member val ShowGlyphWidths: PropKey<bool> = PropKey.Create.simple "CharMap.ShowGlyphWidths"

    member val ShowUnicodeCategory: PropKey<Nullable<System.Globalization.UnicodeCategory>> =
      PropKey.Create.simple "CharMap.ShowUnicodeCategory"

    member val StartCodePoint: PropKey<int> = PropKey.Create.simple "CharMap.StartCodePoint"
    member val Value: PropKey<System.Text.Rune> = PropKey.Create.simple "CharMap.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<System.Text.Rune> -> unit> =
      PropKey.Create.event "CharMap.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "CharMap.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<System.Text.Rune> -> unit> =
      PropKey.Create.event "CharMap.ValueChanging_event"

  type CheckBoxPKeys() =
    inherit ViewPKeys()

    // Properties
    member val AllowCheckStateNone: PropKey<bool> = PropKey.Create.simple "CheckBox.AllowCheckStateNone"
    member val HotKeySpecifier: PropKey<System.Text.Rune> = PropKey.Create.simple "CheckBox.HotKeySpecifier"
    member val RadioStyle: PropKey<bool> = PropKey.Create.simple "CheckBox.RadioStyle"
    member val Text: PropKey<string> = PropKey.Create.simple "CheckBox.Text"
    member val Value: PropKey<Terminal.Gui.Views.CheckState> = PropKey.Create.simple "CheckBox.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.Views.CheckState> -> unit> =
      PropKey.Create.event "CheckBox.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "CheckBox.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.Views.CheckState> -> unit> =
      PropKey.Create.event "CheckBox.ValueChanging_event"

  type ColorPickerPKeys() =
    inherit ViewPKeys()

    // Properties
    member val SelectedColor: PropKey<Terminal.Gui.Drawing.Color> = PropKey.Create.simple "ColorPicker.SelectedColor"
    member val Style: PropKey<Terminal.Gui.Views.ColorPickerStyle> = PropKey.Create.simple "ColorPicker.Style"
    member val Text: PropKey<string> = PropKey.Create.simple "ColorPicker.Text"
    member val Value: PropKey<Nullable<Terminal.Gui.Drawing.Color>> = PropKey.Create.simple "ColorPicker.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<Nullable<Terminal.Gui.Drawing.Color>> -> unit> =
      PropKey.Create.event "ColorPicker.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "ColorPicker.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Nullable<Terminal.Gui.Drawing.Color>> -> unit> =
      PropKey.Create.event "ColorPicker.ValueChanging_event"

  type ColorPicker16PKeys() =
    inherit ViewPKeys()

    // Properties
    member val BoxHeight: PropKey<int> = PropKey.Create.simple "ColorPicker16.BoxHeight"
    member val BoxWidth: PropKey<int> = PropKey.Create.simple "ColorPicker16.BoxWidth"
    member val Caret: PropKey<System.Drawing.Point> = PropKey.Create.simple "ColorPicker16.Caret"

    member val SelectedColor: PropKey<Terminal.Gui.Drawing.ColorName16> =
      PropKey.Create.simple "ColorPicker16.SelectedColor"

    member val Value: PropKey<Terminal.Gui.Drawing.ColorName16> = PropKey.Create.simple "ColorPicker16.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.Drawing.ColorName16> -> unit> =
      PropKey.Create.event "ColorPicker16.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "ColorPicker16.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.Drawing.ColorName16> -> unit> =
      PropKey.Create.event "ColorPicker16.ValueChanging_event"

  type DatePickerPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Culture: PropKey<System.Globalization.CultureInfo> = PropKey.Create.simple "DatePicker.Culture"
    member val Text: PropKey<string> = PropKey.Create.simple "DatePicker.Text"
    member val Value: PropKey<System.DateTime> = PropKey.Create.simple "DatePicker.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<System.DateTime> -> unit> =
      PropKey.Create.event "DatePicker.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "DatePicker.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<System.DateTime> -> unit> =
      PropKey.Create.event "DatePicker.ValueChanging_event"

  type FrameViewPKeys() =
    inherit ViewPKeys()


  type GraphViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val AxisX: PropKey<Terminal.Gui.Views.HorizontalAxis> = PropKey.Create.simple "GraphView.AxisX"
    member val AxisY: PropKey<Terminal.Gui.Views.VerticalAxis> = PropKey.Create.simple "GraphView.AxisY"
    member val CellSize: PropKey<System.Drawing.PointF> = PropKey.Create.simple "GraphView.CellSize"

    member val GraphColor: PropKey<Nullable<Terminal.Gui.Drawing.Attribute>> =
      PropKey.Create.simple "GraphView.GraphColor"

    member val MarginBottom: PropKey<System.UInt32> = PropKey.Create.simple "GraphView.MarginBottom"
    member val MarginLeft: PropKey<System.UInt32> = PropKey.Create.simple "GraphView.MarginLeft"
    member val ScrollOffset: PropKey<System.Drawing.PointF> = PropKey.Create.simple "GraphView.ScrollOffset"

  type HexViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Address: PropKey<System.Int64> = PropKey.Create.simple "HexView.Address"
    member val AddressWidth: PropKey<int> = PropKey.Create.simple "HexView.AddressWidth"
    member val BytesPerLine: PropKey<int> = PropKey.Create.simple "HexView.BytesPerLine"
    member val ReadOnly: PropKey<bool> = PropKey.Create.simple "HexView.ReadOnly"
    member val Source: PropKey<System.IO.Stream> = PropKey.Create.simple "HexView.Source"

    // Events
    member val Edited: PropKey<Terminal.Gui.Views.HexViewEditEventArgs -> unit> =
      PropKey.Create.event "HexView.Edited_event"

    member val PositionChanged: PropKey<Terminal.Gui.Views.HexViewEventArgs -> unit> =
      PropKey.Create.event "HexView.PositionChanged_event"

  type LabelPKeys() =
    inherit ViewPKeys()

    // Properties
    member val HotKeySpecifier: PropKey<System.Text.Rune> = PropKey.Create.simple "Label.HotKeySpecifier"
    member val Text: PropKey<string> = PropKey.Create.simple "Label.Text"

  type LegendAnnotationPKeys() =
    inherit ViewPKeys()


  type LinePKeys() =
    inherit ViewPKeys()

    // Properties
    member val Length: PropKey<Terminal.Gui.ViewBase.Dim> = PropKey.Create.simple "Line.Length"
    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> = PropKey.Create.simple "Line.Orientation"
    member val Style: PropKey<Terminal.Gui.Drawing.LineStyle> = PropKey.Create.simple "Line.Style"

    // Events
    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "Line.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "Line.OrientationChanging_event"

  type LinearRangePKeys<'T>() =
    inherit ViewPKeys()

    // Properties
    member val AllowEmpty: PropKey<bool> = PropKey.Create.simple "LinearRange.AllowEmpty"
    member val FocusedOption: PropKey<int> = PropKey.Create.simple "LinearRange.FocusedOption"

    member val LegendsOrientation: PropKey<Terminal.Gui.ViewBase.Orientation> =
      PropKey.Create.simple "LinearRange.LegendsOrientation"

    member val MinimumInnerSpacing: PropKey<int> = PropKey.Create.simple "LinearRange.MinimumInnerSpacing"
    member val Options: PropKey<List<LinearRangeOption<'T>>> = PropKey.Create.simple "LinearRange.Options"
    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> = PropKey.Create.simple "LinearRange.Orientation"
    member val RangeAllowSingle: PropKey<bool> = PropKey.Create.simple "LinearRange.RangeAllowSingle"
    member val ShowEndSpacing: PropKey<bool> = PropKey.Create.simple "LinearRange.ShowEndSpacing"
    member val ShowLegends: PropKey<bool> = PropKey.Create.simple "LinearRange.ShowLegends"
    member val Style: PropKey<Terminal.Gui.Views.LinearRangeStyle> = PropKey.Create.simple "LinearRange.Style"
    member val Text: PropKey<string> = PropKey.Create.simple "LinearRange.Text"
    member val Type: PropKey<Terminal.Gui.Views.LinearRangeType> = PropKey.Create.simple "LinearRange.Type"
    member val UseMinimumSize: PropKey<bool> = PropKey.Create.simple "LinearRange.UseMinimumSize"

    // Events
    member val LegendsOrientationChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "LinearRange.LegendsOrientationChanged_event"

    member val LegendsOrientationChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "LinearRange.LegendsOrientationChanging_event"

    member val MinimumInnerSpacingChanged: PropKey<ValueChangedEventArgs<int> -> unit> =
      PropKey.Create.event "LinearRange.MinimumInnerSpacingChanged_event"

    member val MinimumInnerSpacingChanging: PropKey<ValueChangingEventArgs<int> -> unit> =
      PropKey.Create.event "LinearRange.MinimumInnerSpacingChanging_event"

    member val OptionFocused: PropKey<LinearRangeEventArgs<'T> -> unit> =
      PropKey.Create.event "LinearRange.OptionFocused_event"

    member val OptionsChanged: PropKey<LinearRangeEventArgs<'T> -> unit> =
      PropKey.Create.event "LinearRange.OptionsChanged_event"

    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "LinearRange.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "LinearRange.OrientationChanging_event"

    member val ShowEndSpacingChanged: PropKey<ValueChangedEventArgs<bool> -> unit> =
      PropKey.Create.event "LinearRange.ShowEndSpacingChanged_event"

    member val ShowEndSpacingChanging: PropKey<ValueChangingEventArgs<bool> -> unit> =
      PropKey.Create.event "LinearRange.ShowEndSpacingChanging_event"

    member val ShowLegendsChanged: PropKey<ValueChangedEventArgs<bool> -> unit> =
      PropKey.Create.event "LinearRange.ShowLegendsChanged_event"

    member val ShowLegendsChanging: PropKey<ValueChangingEventArgs<bool> -> unit> =
      PropKey.Create.event "LinearRange.ShowLegendsChanging_event"

    member val TypeChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.Views.LinearRangeType> -> unit> =
      PropKey.Create.event "LinearRange.TypeChanged_event"

    member val TypeChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.Views.LinearRangeType> -> unit> =
      PropKey.Create.event "LinearRange.TypeChanging_event"

    member val UseMinimumSizeChanged: PropKey<ValueChangedEventArgs<bool> -> unit> =
      PropKey.Create.event "LinearRange.UseMinimumSizeChanged_event"

    member val UseMinimumSizeChanging: PropKey<ValueChangingEventArgs<bool> -> unit> =
      PropKey.Create.event "LinearRange.UseMinimumSizeChanging_event"

  type LinearRangePKeys() =
    inherit LinearRangePKeys<System.Object>()


  type LinkPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Url: PropKey<string> = PropKey.Create.simple "Link.Url"

    // Events
    member val UrlChanged: PropKey<ValueChangedEventArgs<string> -> unit> = PropKey.Create.event "Link.UrlChanged_event"

    member val UrlChanging: PropKey<ValueChangingEventArgs<string> -> unit> =
      PropKey.Create.event "Link.UrlChanging_event"

  type ListViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val MarkMultiple: PropKey<bool> = PropKey.Create.simple "ListView.MarkMultiple"
    member val SelectedItem: PropKey<Nullable<int>> = PropKey.Create.simple "ListView.SelectedItem"
    member val ShowMarks: PropKey<bool> = PropKey.Create.simple "ListView.ShowMarks"
    member val Source: PropKey<Terminal.Gui.Views.IListDataSource> = PropKey.Create.simple "ListView.Source"
    member val Value: PropKey<Nullable<int>> = PropKey.Create.simple "ListView.Value"

    // Events
    member val CollectionChanged: PropKey<System.Collections.Specialized.NotifyCollectionChangedEventArgs -> unit> =
      PropKey.Create.event "ListView.CollectionChanged_event"

    member val RowRender: PropKey<Terminal.Gui.Views.ListViewRowEventArgs -> unit> =
      PropKey.Create.event "ListView.RowRender_event"

    member val SourceChanged: PropKey<System.EventArgs -> unit> = PropKey.Create.event "ListView.SourceChanged_event"

    member val ValueChanged: PropKey<ValueChangedEventArgs<Nullable<int>> -> unit> =
      PropKey.Create.event "ListView.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "ListView.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Nullable<int>> -> unit> =
      PropKey.Create.event "ListView.ValueChanging_event"

  type MarginPKeys() =
    inherit AdornmentPKeys()

    // Properties
    member val ShadowSize: PropKey<System.Drawing.Size> = PropKey.Create.simple "Margin.ShadowSize"
    member val ShadowStyle: PropKey<Terminal.Gui.ViewBase.ShadowStyle> = PropKey.Create.simple "Margin.ShadowStyle"

  type MenuPKeys() =
    inherit BarPKeys()

    // Properties
    member val SuperMenuItem: PropKey<Terminal.Gui.Views.MenuItem> = PropKey.Create.view "Menu.SuperMenuItem_view"

    member val SuperMenuItem_element: PropKey<IMenuItemTerminalElement> =
      PropKey.Create.subElement "Menu.SuperMenuItem_element"

    member val Value: PropKey<Terminal.Gui.Views.MenuItem> = PropKey.Create.view "Menu.Value_view"
    member val Value_element: PropKey<IMenuItemTerminalElement> = PropKey.Create.subElement "Menu.Value_element"

    // Events
    member val SelectedMenuItemChanged: PropKey<Terminal.Gui.Views.MenuItem -> unit> =
      PropKey.Create.event "Menu.SelectedMenuItemChanged_event"

    member val ValueChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.Views.MenuItem> -> unit> =
      PropKey.Create.event "Menu.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "Menu.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.Views.MenuItem> -> unit> =
      PropKey.Create.event "Menu.ValueChanging_event"

  type MenuBarPKeys() =
    inherit MenuPKeys()

    // Properties
    member val Key: PropKey<Terminal.Gui.Input.Key> = PropKey.Create.simple "MenuBar.Key"

    // Events
    member val KeyChanged: PropKey<Terminal.Gui.Input.KeyChangedEventArgs -> unit> =
      PropKey.Create.event "MenuBar.KeyChanged_event"

  type NumericUpDownPKeys<'T>() =
    inherit ViewPKeys()

    // Properties
    member val Format: PropKey<string> = PropKey.Create.simple "NumericUpDown.Format"
    member val Increment: PropKey<'T> = PropKey.Create.simple "NumericUpDown.Increment"
    member val Value: PropKey<'T> = PropKey.Create.simple "NumericUpDown.Value"

    // Events
    member val FormatChanged: PropKey<EventArgs<string> -> unit> =
      PropKey.Create.event "NumericUpDown.FormatChanged_event"

    member val IncrementChanged: PropKey<EventArgs<'T> -> unit> =
      PropKey.Create.event "NumericUpDown.IncrementChanged_event"

    member val ValueChanged: PropKey<ValueChangedEventArgs<'T> -> unit> =
      PropKey.Create.event "NumericUpDown.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "NumericUpDown.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<'T> -> unit> =
      PropKey.Create.event "NumericUpDown.ValueChanging_event"

  type NumericUpDownPKeys() =
    inherit NumericUpDownPKeys<int>()


  type PaddingPKeys() =
    inherit AdornmentPKeys()


  type PopoverImplPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Anchor: PropKey<Func<Nullable<System.Drawing.Rectangle>>> = PropKey.Create.simple "PopoverImpl.Anchor"
    member val Owner: PropKey<Terminal.Gui.App.IRunnable> = PropKey.Create.simple "PopoverImpl.Owner"
    member val Target: PropKey<WeakReference<Terminal.Gui.ViewBase.View>> = PropKey.Create.simple "PopoverImpl.Target"

  type PopoverPKeys<'TView, 'TResult when 'TView: (new: unit -> 'TView) and 'TView :> Terminal.Gui.ViewBase.View>() =
    inherit PopoverImplPKeys()

    // Properties
    member val ContentView: PropKey<'TView> = PropKey.Create.view "Popover.ContentView_view"

    member val ContentView_element: PropKey<ITViewTerminalElement> =
      PropKey.Create.subElement "Popover.ContentView_element"

    member val ResultExtractor: PropKey<Func<'TView, 'TResult>> = PropKey.Create.simple "Popover.ResultExtractor"

    // Events
    member val ResultChanged: PropKey<ValueChangedEventArgs<'TResult> -> unit> =
      PropKey.Create.event "Popover.ResultChanged_event"

  type PopoverMenuPKeys() =
    inherit PopoverPKeys<Terminal.Gui.Views.Menu, Terminal.Gui.Views.MenuItem>()

    // Properties
    member val Key: PropKey<Terminal.Gui.Input.Key> = PropKey.Create.simple "PopoverMenu.Key"
    member val MouseFlags: PropKey<Terminal.Gui.Input.MouseFlags> = PropKey.Create.simple "PopoverMenu.MouseFlags"
    member val Root: PropKey<Terminal.Gui.Views.Menu> = PropKey.Create.view "PopoverMenu.Root_view"
    member val Root_element: PropKey<IMenuTerminalElement> = PropKey.Create.subElement "PopoverMenu.Root_element"

    // Events
    member val KeyChanged: PropKey<Terminal.Gui.Input.KeyChangedEventArgs -> unit> =
      PropKey.Create.event "PopoverMenu.KeyChanged_event"

  type ProgressBarPKeys() =
    inherit ViewPKeys()

    // Properties
    member val BidirectionalMarquee: PropKey<bool> = PropKey.Create.simple "ProgressBar.BidirectionalMarquee"
    member val Fraction: PropKey<System.Single> = PropKey.Create.simple "ProgressBar.Fraction"

    member val ProgressBarFormat: PropKey<Terminal.Gui.Views.ProgressBarFormat> =
      PropKey.Create.simple "ProgressBar.ProgressBarFormat"

    member val ProgressBarStyle: PropKey<Terminal.Gui.Views.ProgressBarStyle> =
      PropKey.Create.simple "ProgressBar.ProgressBarStyle"

    member val SegmentCharacter: PropKey<System.Text.Rune> = PropKey.Create.simple "ProgressBar.SegmentCharacter"
    member val Text: PropKey<string> = PropKey.Create.simple "ProgressBar.Text"

  type RunnablePKeys() =
    inherit ViewPKeys()

    // Properties
    member val Result: PropKey<System.Object> = PropKey.Create.simple "Runnable.Result"
    member val StopRequested: PropKey<bool> = PropKey.Create.simple "Runnable.StopRequested"

    // Events
    member val IsModalChanged: PropKey<EventArgs<bool> -> unit> = PropKey.Create.event "Runnable.IsModalChanged_event"

    member val IsRunningChanged: PropKey<EventArgs<bool> -> unit> =
      PropKey.Create.event "Runnable.IsRunningChanged_event"

    member val IsRunningChanging: PropKey<CancelEventArgs<bool> -> unit> =
      PropKey.Create.event "Runnable.IsRunningChanging_event"

  type RunnablePKeys<'TResult>() =
    inherit RunnablePKeys()

    // Properties
    member val Result: PropKey<'TResult> = PropKey.Create.simple "Runnable.Result"

  type DialogPKeys<'TResult>() =
    inherit RunnablePKeys<'TResult>()

    // Properties
    member val ButtonAlignment: PropKey<Terminal.Gui.ViewBase.Alignment> =
      PropKey.Create.simple "Dialog.ButtonAlignment"

    member val ButtonAlignmentModes: PropKey<Terminal.Gui.ViewBase.AlignmentModes> =
      PropKey.Create.simple "Dialog.ButtonAlignmentModes"

    member val Buttons: PropKey<Terminal.Gui.Views.Button[]> = PropKey.Create.simple "Dialog.Buttons"

  type DialogPKeys() =
    inherit DialogPKeys<int>()

    // Properties
    member val Result: PropKey<Nullable<int>> = PropKey.Create.simple "Dialog.Result"

  type PromptPKeys<'TView, 'TResult when 'TView: (new: unit -> 'TView) and 'TView :> Terminal.Gui.ViewBase.View>() =
    inherit DialogPKeys<'TResult>()

    // Properties
    member val ResultExtractor: PropKey<Func<'TView, 'TResult>> = PropKey.Create.simple "Prompt.ResultExtractor"

  type FileDialogPKeys() =
    inherit DialogPKeys()

    // Properties
    member val AllowedTypes: PropKey<List<Terminal.Gui.Views.IAllowedType>> =
      PropKey.Create.simple "FileDialog.AllowedTypes"

    member val AllowsMultipleSelection: PropKey<bool> = PropKey.Create.simple "FileDialog.AllowsMultipleSelection"

    member val FileOperationsHandler: PropKey<Terminal.Gui.FileServices.IFileOperations> =
      PropKey.Create.simple "FileDialog.FileOperationsHandler"

    member val MustExist: PropKey<bool> = PropKey.Create.simple "FileDialog.MustExist"
    member val OpenMode: PropKey<Terminal.Gui.Views.OpenMode> = PropKey.Create.simple "FileDialog.OpenMode"
    member val Path: PropKey<string> = PropKey.Create.simple "FileDialog.Path"

    member val SearchMatcher: PropKey<Terminal.Gui.FileServices.ISearchMatcher> =
      PropKey.Create.simple "FileDialog.SearchMatcher"

    // Events
    member val FilesSelected: PropKey<Terminal.Gui.Views.FilesSelectedEventArgs -> unit> =
      PropKey.Create.event "FileDialog.FilesSelected_event"

  type OpenDialogPKeys() =
    inherit FileDialogPKeys()

    // Properties
    member val OpenMode: PropKey<Terminal.Gui.Views.OpenMode> = PropKey.Create.simple "OpenDialog.OpenMode"

  type SaveDialogPKeys() =
    inherit FileDialogPKeys()


  type ScrollBarPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Increment: PropKey<int> = PropKey.Create.simple "ScrollBar.Increment"
    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> = PropKey.Create.simple "ScrollBar.Orientation"
    member val ScrollableContentSize: PropKey<int> = PropKey.Create.simple "ScrollBar.ScrollableContentSize"
    member val Value: PropKey<int> = PropKey.Create.simple "ScrollBar.Value"

    member val VisibilityMode: PropKey<Terminal.Gui.Views.ScrollBarVisibilityMode> =
      PropKey.Create.simple "ScrollBar.VisibilityMode"

    member val VisibleContentSize: PropKey<int> = PropKey.Create.simple "ScrollBar.VisibleContentSize"

    // Events
    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "ScrollBar.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "ScrollBar.OrientationChanging_event"

    member val ScrollableContentSizeChanged: PropKey<EventArgs<int> -> unit> =
      PropKey.Create.event "ScrollBar.ScrollableContentSizeChanged_event"

    member val Scrolled: PropKey<EventArgs<int> -> unit> = PropKey.Create.event "ScrollBar.Scrolled_event"

    member val SliderPositionChanged: PropKey<EventArgs<int> -> unit> =
      PropKey.Create.event "ScrollBar.SliderPositionChanged_event"

    member val ValueChanged: PropKey<ValueChangedEventArgs<int> -> unit> =
      PropKey.Create.event "ScrollBar.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "ScrollBar.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<int> -> unit> =
      PropKey.Create.event "ScrollBar.ValueChanging_event"

  type ScrollSliderPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> =
      PropKey.Create.simple "ScrollSlider.Orientation"

    member val Position: PropKey<int> = PropKey.Create.simple "ScrollSlider.Position"
    member val Size: PropKey<int> = PropKey.Create.simple "ScrollSlider.Size"
    member val SliderPadding: PropKey<int> = PropKey.Create.simple "ScrollSlider.SliderPadding"
    member val VisibleContentSize: PropKey<int> = PropKey.Create.simple "ScrollSlider.VisibleContentSize"

    // Events
    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "ScrollSlider.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "ScrollSlider.OrientationChanging_event"

    member val PositionChanged: PropKey<EventArgs<int> -> unit> =
      PropKey.Create.event "ScrollSlider.PositionChanged_event"

    member val PositionChanging: PropKey<CancelEventArgs<int> -> unit> =
      PropKey.Create.event "ScrollSlider.PositionChanging_event"

    member val Scrolled: PropKey<EventArgs<int> -> unit> = PropKey.Create.event "ScrollSlider.Scrolled_event"

  type SelectorBasePKeys() =
    inherit ViewPKeys()

    // Properties
    member val DoubleClickAccepts: PropKey<bool> = PropKey.Create.simple "SelectorBase.DoubleClickAccepts"
    member val HorizontalSpace: PropKey<int> = PropKey.Create.simple "SelectorBase.HorizontalSpace"
    member val Labels: PropKey<IReadOnlyList<string>> = PropKey.Create.simple "SelectorBase.Labels"

    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> =
      PropKey.Create.simple "SelectorBase.Orientation"

    member val Styles: PropKey<Terminal.Gui.Views.SelectorStyles> = PropKey.Create.simple "SelectorBase.Styles"

    member val TabBehavior: PropKey<Nullable<Terminal.Gui.ViewBase.TabBehavior>> =
      PropKey.Create.simple "SelectorBase.TabBehavior"

    member val Value: PropKey<Nullable<int>> = PropKey.Create.simple "SelectorBase.Value"
    member val Values: PropKey<IReadOnlyList<int>> = PropKey.Create.simple "SelectorBase.Values"

    // Events
    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "SelectorBase.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "SelectorBase.OrientationChanging_event"

    member val ValueChanged: PropKey<ValueChangedEventArgs<Nullable<int>> -> unit> =
      PropKey.Create.event "SelectorBase.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "SelectorBase.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<Nullable<int>> -> unit> =
      PropKey.Create.event "SelectorBase.ValueChanging_event"

  type FlagSelectorPKeys() =
    inherit SelectorBasePKeys()

    // Properties
    member val Value: PropKey<Nullable<int>> = PropKey.Create.simple "FlagSelector.Value"

  type OptionSelectorPKeys() =
    inherit SelectorBasePKeys()

    // Properties
    member val FocusedItem: PropKey<int> = PropKey.Create.simple "OptionSelector.FocusedItem"

  type FlagSelectorPKeys<'TFlagsEnum
    when 'TFlagsEnum: struct
    and 'TFlagsEnum: (new: unit -> 'TFlagsEnum)
    and 'TFlagsEnum :> System.Enum
    and 'TFlagsEnum :> System.ValueType>() =
    inherit FlagSelectorPKeys()

    // Properties
    member val Value: PropKey<Nullable<'TFlagsEnum>> = PropKey.Create.simple "FlagSelector.Value"

    // Events
    member val ValueChanged: PropKey<EventArgs<Nullable<'TFlagsEnum>> -> unit> =
      PropKey.Create.event "FlagSelector.ValueChanged_event"

  type OptionSelectorPKeys<'TEnum
    when 'TEnum: struct and 'TEnum: (new: unit -> 'TEnum) and 'TEnum :> System.Enum and 'TEnum :> System.ValueType>() =
    inherit OptionSelectorPKeys()

    // Properties
    member val Value: PropKey<Nullable<'TEnum>> = PropKey.Create.simple "OptionSelector.Value"
    member val Values: PropKey<IReadOnlyList<int>> = PropKey.Create.simple "OptionSelector.Values"

    // Events
    member val ValueChanged: PropKey<EventArgs<Nullable<'TEnum>> -> unit> =
      PropKey.Create.event "OptionSelector.ValueChanged_event"

  type ShortcutPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Action: PropKey<System.Action> = PropKey.Create.simple "Shortcut.Action"

    member val AlignmentModes: PropKey<Terminal.Gui.ViewBase.AlignmentModes> =
      PropKey.Create.simple "Shortcut.AlignmentModes"

    member val BindKeyToApplication: PropKey<bool> = PropKey.Create.simple "Shortcut.BindKeyToApplication"
    member val Command: PropKey<Terminal.Gui.Input.Command> = PropKey.Create.simple "Shortcut.Command"
    member val CommandView: PropKey<Terminal.Gui.ViewBase.View> = PropKey.Create.view "Shortcut.CommandView_view"
    member val CommandView_element: PropKey<ITerminalElement> = PropKey.Create.subElement "Shortcut.CommandView_element"
    member val HelpText: PropKey<string> = PropKey.Create.simple "Shortcut.HelpText"
    member val Key: PropKey<Terminal.Gui.Input.Key> = PropKey.Create.simple "Shortcut.Key"
    member val MinimumKeyTextSize: PropKey<int> = PropKey.Create.simple "Shortcut.MinimumKeyTextSize"
    member val Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> = PropKey.Create.simple "Shortcut.Orientation"
    member val TargetView: PropKey<Terminal.Gui.ViewBase.View> = PropKey.Create.view "Shortcut.TargetView_view"
    member val TargetView_element: PropKey<ITerminalElement> = PropKey.Create.subElement "Shortcut.TargetView_element"
    member val Text: PropKey<string> = PropKey.Create.simple "Shortcut.Text"

    // Events
    member val OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "Shortcut.OrientationChanged_event"

    member val OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "Shortcut.OrientationChanging_event"

  type MenuItemPKeys() =
    inherit ShortcutPKeys()

    // Properties
    member val SubMenu: PropKey<Terminal.Gui.Views.Menu> = PropKey.Create.view "MenuItem.SubMenu_view"
    member val SubMenu_element: PropKey<IMenuTerminalElement> = PropKey.Create.subElement "MenuItem.SubMenu_element"

  type MenuBarItemPKeys() =
    inherit MenuItemPKeys()

    // Properties
    member val PopoverMenu: PropKey<Terminal.Gui.Views.PopoverMenu> = PropKey.Create.view "MenuBarItem.PopoverMenu_view"

    member val PopoverMenu_element: PropKey<IPopoverMenuTerminalElement> =
      PropKey.Create.subElement "MenuBarItem.PopoverMenu_element"

    member val PopoverMenuOpen: PropKey<bool> = PropKey.Create.simple "MenuBarItem.PopoverMenuOpen"

    // Events
    member val MenuOpenChanged: PropKey<ValueChangedEventArgs<bool> -> unit> =
      PropKey.Create.event "MenuBarItem.MenuOpenChanged_event"

    member val PopoverMenuOpenChanged: PropKey<ValueChangedEventArgs<bool> -> unit> =
      PropKey.Create.event "MenuBarItem.PopoverMenuOpenChanged_event"

  type SpinnerViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val AutoSpin: PropKey<bool> = PropKey.Create.simple "SpinnerView.AutoSpin"
    member val Sequence: PropKey<System.String[]> = PropKey.Create.simple "SpinnerView.Sequence"
    member val SpinBounce: PropKey<bool> = PropKey.Create.simple "SpinnerView.SpinBounce"
    member val SpinDelay: PropKey<int> = PropKey.Create.simple "SpinnerView.SpinDelay"
    member val SpinReverse: PropKey<bool> = PropKey.Create.simple "SpinnerView.SpinReverse"
    member val Style: PropKey<Terminal.Gui.Views.SpinnerStyle> = PropKey.Create.simple "SpinnerView.Style"

  type StatusBarPKeys() =
    inherit BarPKeys()


  type TabPKeys() =
    inherit ViewPKeys()

    // Properties
    member val DisplayText: PropKey<string> = PropKey.Create.simple "Tab.DisplayText"
    member val View: PropKey<Terminal.Gui.ViewBase.View> = PropKey.Create.view "Tab.View_view"
    member val View_element: PropKey<ITerminalElement> = PropKey.Create.subElement "Tab.View_element"

  type TabViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val MaxTabTextWidth: PropKey<System.UInt32> = PropKey.Create.simple "TabView.MaxTabTextWidth"
    member val SelectedTab: PropKey<Terminal.Gui.Views.Tab> = PropKey.Create.view "TabView.SelectedTab_view"

    member val SelectedTab_element: PropKey<ITabTerminalElement> =
      PropKey.Create.subElement "TabView.SelectedTab_element"

    member val Style: PropKey<Terminal.Gui.Views.TabStyle> = PropKey.Create.simple "TabView.Style"
    member val TabScrollOffset: PropKey<int> = PropKey.Create.simple "TabView.TabScrollOffset"

    // Events
    member val SelectedTabChanged: PropKey<Terminal.Gui.Views.TabChangedEventArgs -> unit> =
      PropKey.Create.event "TabView.SelectedTabChanged_event"

    member val TabClicked: PropKey<Terminal.Gui.Views.TabMouseEventArgs -> unit> =
      PropKey.Create.event "TabView.TabClicked_event"

  type TableViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val CellActivationKey: PropKey<Terminal.Gui.Drivers.KeyCode> =
      PropKey.Create.simple "TableView.CellActivationKey"

    member val CollectionNavigator: PropKey<Terminal.Gui.Views.ICollectionNavigator> =
      PropKey.Create.simple "TableView.CollectionNavigator"

    member val ColumnOffset: PropKey<int> = PropKey.Create.simple "TableView.ColumnOffset"
    member val FullRowSelect: PropKey<bool> = PropKey.Create.simple "TableView.FullRowSelect"
    member val MaxCellWidth: PropKey<int> = PropKey.Create.simple "TableView.MaxCellWidth"
    member val MinCellWidth: PropKey<int> = PropKey.Create.simple "TableView.MinCellWidth"
    member val MultiSelect: PropKey<bool> = PropKey.Create.simple "TableView.MultiSelect"
    member val NullSymbol: PropKey<string> = PropKey.Create.simple "TableView.NullSymbol"
    member val RowOffset: PropKey<int> = PropKey.Create.simple "TableView.RowOffset"
    member val SelectedColumn: PropKey<int> = PropKey.Create.simple "TableView.SelectedColumn"
    member val SelectedRow: PropKey<int> = PropKey.Create.simple "TableView.SelectedRow"
    member val SeparatorSymbol: PropKey<System.Char> = PropKey.Create.simple "TableView.SeparatorSymbol"
    member val Style: PropKey<Terminal.Gui.Views.TableStyle> = PropKey.Create.simple "TableView.Style"
    member val Table: PropKey<Terminal.Gui.Views.ITableSource> = PropKey.Create.simple "TableView.Table"

    member val UseAllRowsForContentCalculation: PropKey<bool> =
      PropKey.Create.simple "TableView.UseAllRowsForContentCalculation"

    // Events
    member val CellActivated: PropKey<Terminal.Gui.Views.CellActivatedEventArgs -> unit> =
      PropKey.Create.event "TableView.CellActivated_event"

    member val CellToggled: PropKey<Terminal.Gui.Views.CellToggledEventArgs -> unit> =
      PropKey.Create.event "TableView.CellToggled_event"

    member val SelectedCellChanged: PropKey<Terminal.Gui.Views.SelectedCellChangedEventArgs -> unit> =
      PropKey.Create.event "TableView.SelectedCellChanged_event"

  type TextFieldPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Autocomplete: PropKey<Terminal.Gui.Views.IAutocomplete> = PropKey.Create.simple "TextField.Autocomplete"
    member val InsertionPoint: PropKey<int> = PropKey.Create.simple "TextField.InsertionPoint"
    member val ReadOnly: PropKey<bool> = PropKey.Create.simple "TextField.ReadOnly"
    member val Secret: PropKey<bool> = PropKey.Create.simple "TextField.Secret"

    member val SelectWordOnlyOnDoubleClick: PropKey<bool> =
      PropKey.Create.simple "TextField.SelectWordOnlyOnDoubleClick"

    member val SelectedStart: PropKey<int> = PropKey.Create.simple "TextField.SelectedStart"
    member val Text: PropKey<string> = PropKey.Create.simple "TextField.Text"
    member val UseSameRuneTypeForWords: PropKey<bool> = PropKey.Create.simple "TextField.UseSameRuneTypeForWords"
    member val Used: PropKey<bool> = PropKey.Create.simple "TextField.Used"
    member val Value: PropKey<string> = PropKey.Create.simple "TextField.Value"

    // Events
    member val TextChanging: PropKey<ResultEventArgs<string> -> unit> =
      PropKey.Create.event "TextField.TextChanging_event"

    member val ValueChanged: PropKey<ValueChangedEventArgs<string> -> unit> =
      PropKey.Create.event "TextField.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "TextField.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<string> -> unit> =
      PropKey.Create.event "TextField.ValueChanging_event"

  type DropDownListPKeys() =
    inherit TextFieldPKeys()

    // Properties
    member val Source: PropKey<Terminal.Gui.Views.IListDataSource> = PropKey.Create.simple "DropDownList.Source"

  type TextValidateFieldPKeys() =
    inherit ViewPKeys()

    // Properties
    member val Provider: PropKey<Terminal.Gui.Views.ITextValidateProvider> =
      PropKey.Create.simple "TextValidateField.Provider"

    member val Text: PropKey<string> = PropKey.Create.simple "TextValidateField.Text"
    member val Value: PropKey<string> = PropKey.Create.simple "TextValidateField.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<string> -> unit> =
      PropKey.Create.event "TextValidateField.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "TextValidateField.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<string> -> unit> =
      PropKey.Create.event "TextValidateField.ValueChanging_event"

  type DateEditorPKeys() =
    inherit TextValidateFieldPKeys()

    // Properties
    member val Format: PropKey<System.Globalization.DateTimeFormatInfo> = PropKey.Create.simple "DateEditor.Format"
    member val Value: PropKey<System.DateTime> = PropKey.Create.simple "DateEditor.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<System.DateTime> -> unit> =
      PropKey.Create.event "DateEditor.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "DateEditor.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<System.DateTime> -> unit> =
      PropKey.Create.event "DateEditor.ValueChanging_event"

  type TextViewPKeys() =
    inherit ViewPKeys()

    // Properties
    member val EnterKeyAddsLine: PropKey<bool> = PropKey.Create.simple "TextView.EnterKeyAddsLine"
    member val InheritsPreviousAttribute: PropKey<bool> = PropKey.Create.simple "TextView.InheritsPreviousAttribute"
    member val InsertionPoint: PropKey<System.Drawing.Point> = PropKey.Create.simple "TextView.InsertionPoint"
    member val IsSelecting: PropKey<bool> = PropKey.Create.simple "TextView.IsSelecting"
    member val Multiline: PropKey<bool> = PropKey.Create.simple "TextView.Multiline"
    member val ReadOnly: PropKey<bool> = PropKey.Create.simple "TextView.ReadOnly"
    member val ScrollBars: PropKey<bool> = PropKey.Create.simple "TextView.ScrollBars"
    member val SelectWordOnlyOnDoubleClick: PropKey<bool> = PropKey.Create.simple "TextView.SelectWordOnlyOnDoubleClick"
    member val SelectionStartColumn: PropKey<int> = PropKey.Create.simple "TextView.SelectionStartColumn"
    member val SelectionStartRow: PropKey<int> = PropKey.Create.simple "TextView.SelectionStartRow"
    member val TabKeyAddsTab: PropKey<bool> = PropKey.Create.simple "TextView.TabKeyAddsTab"
    member val TabWidth: PropKey<int> = PropKey.Create.simple "TextView.TabWidth"
    member val Text: PropKey<string> = PropKey.Create.simple "TextView.Text"
    member val UseSameRuneTypeForWords: PropKey<bool> = PropKey.Create.simple "TextView.UseSameRuneTypeForWords"
    member val Used: PropKey<bool> = PropKey.Create.simple "TextView.Used"
    member val WordWrap: PropKey<bool> = PropKey.Create.simple "TextView.WordWrap"

    // Events
    member val ContentsChanged: PropKey<Terminal.Gui.Views.ContentsChangedEventArgs -> unit> =
      PropKey.Create.event "TextView.ContentsChanged_event"

    member val DrawNormalColor: PropKey<Terminal.Gui.Drawing.CellEventArgs -> unit> =
      PropKey.Create.event "TextView.DrawNormalColor_event"

    member val DrawReadOnlyColor: PropKey<Terminal.Gui.Drawing.CellEventArgs -> unit> =
      PropKey.Create.event "TextView.DrawReadOnlyColor_event"

    member val DrawSelectionColor: PropKey<Terminal.Gui.Drawing.CellEventArgs -> unit> =
      PropKey.Create.event "TextView.DrawSelectionColor_event"

    member val DrawUsedColor: PropKey<Terminal.Gui.Drawing.CellEventArgs -> unit> =
      PropKey.Create.event "TextView.DrawUsedColor_event"

    member val UnwrappedCursorPositionChanged: PropKey<System.Drawing.Point -> unit> =
      PropKey.Create.event "TextView.UnwrappedCursorPositionChanged_event"

  type TimeEditorPKeys() =
    inherit TextValidateFieldPKeys()

    // Properties
    member val Format: PropKey<System.Globalization.DateTimeFormatInfo> = PropKey.Create.simple "TimeEditor.Format"
    member val Value: PropKey<System.TimeSpan> = PropKey.Create.simple "TimeEditor.Value"

    // Events
    member val ValueChanged: PropKey<ValueChangedEventArgs<System.TimeSpan> -> unit> =
      PropKey.Create.event "TimeEditor.ValueChanged_event"

    member val ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "TimeEditor.ValueChangedUntyped_event"

    member val ValueChanging: PropKey<ValueChangingEventArgs<System.TimeSpan> -> unit> =
      PropKey.Create.event "TimeEditor.ValueChanging_event"

  type TreeViewPKeys<'T when 'T: not struct>() =
    inherit ViewPKeys()

    // Properties
    member val AllowLetterBasedNavigation: PropKey<bool> = PropKey.Create.simple "TreeView.AllowLetterBasedNavigation"
    member val AspectGetter: PropKey<AspectGetterDelegate<'T>> = PropKey.Create.simple "TreeView.AspectGetter"

    member val ColorGetter: PropKey<Func<'T, Terminal.Gui.Drawing.Scheme>> =
      PropKey.Create.simple "TreeView.ColorGetter"

    member val MaxDepth: PropKey<int> = PropKey.Create.simple "TreeView.MaxDepth"
    member val MultiSelect: PropKey<bool> = PropKey.Create.simple "TreeView.MultiSelect"

    member val ObjectActivationButton: PropKey<Nullable<Terminal.Gui.Input.MouseFlags>> =
      PropKey.Create.simple "TreeView.ObjectActivationButton"

    member val ObjectActivationKey: PropKey<Terminal.Gui.Drivers.KeyCode> =
      PropKey.Create.simple "TreeView.ObjectActivationKey"

    member val ScrollOffsetHorizontal: PropKey<int> = PropKey.Create.simple "TreeView.ScrollOffsetHorizontal"
    member val ScrollOffsetVertical: PropKey<int> = PropKey.Create.simple "TreeView.ScrollOffsetVertical"
    member val SelectedObject: PropKey<'T> = PropKey.Create.simple "TreeView.SelectedObject"
    member val Style: PropKey<Terminal.Gui.Views.TreeStyle> = PropKey.Create.simple "TreeView.Style"
    member val TreeBuilder: PropKey<ITreeBuilder<'T>> = PropKey.Create.simple "TreeView.TreeBuilder"

    // Events
    member val DrawLine: PropKey<DrawTreeViewLineEventArgs<'T> -> unit> = PropKey.Create.event "TreeView.DrawLine_event"

    member val ObjectActivated: PropKey<ObjectActivatedEventArgs<'T> -> unit> =
      PropKey.Create.event "TreeView.ObjectActivated_event"

    member val SelectionChanged: PropKey<SelectionChangedEventArgs<'T> -> unit> =
      PropKey.Create.event "TreeView.SelectionChanged_event"

  type TreeViewPKeys() =
    inherit TreeViewPKeys<Terminal.Gui.Views.ITreeNode>()


  type WindowPKeys() =
    inherit RunnablePKeys()


  type WizardPKeys() =
    inherit DialogPKeys()

    // Properties
    member val CurrentStep: PropKey<Terminal.Gui.Views.WizardStep> = PropKey.Create.view "Wizard.CurrentStep_view"

    member val CurrentStep_element: PropKey<IWizardStepTerminalElement> =
      PropKey.Create.subElement "Wizard.CurrentStep_element"

    // Events
    member val MovingBack: PropKey<System.ComponentModel.CancelEventArgs -> unit> =
      PropKey.Create.event "Wizard.MovingBack_event"

    member val MovingNext: PropKey<System.ComponentModel.CancelEventArgs -> unit> =
      PropKey.Create.event "Wizard.MovingNext_event"

    member val StepChanged: PropKey<ValueChangedEventArgs<Terminal.Gui.Views.WizardStep> -> unit> =
      PropKey.Create.event "Wizard.StepChanged_event"

    member val StepChanging: PropKey<ValueChangingEventArgs<Terminal.Gui.Views.WizardStep> -> unit> =
      PropKey.Create.event "Wizard.StepChanging_event"

  type WizardStepPKeys() =
    inherit ViewPKeys()

    // Properties
    member val BackButtonText: PropKey<string> = PropKey.Create.simple "WizardStep.BackButtonText"
    member val HelpText: PropKey<string> = PropKey.Create.simple "WizardStep.HelpText"
    member val NextButtonText: PropKey<string> = PropKey.Create.simple "WizardStep.NextButtonText"

  module internal IMouseHoldRepeaterInterface =
    // Properties
    let Timeout: PropKey<Terminal.Gui.App.Timeout> =
      PropKey.Create.simple "IMouseHoldRepeaterInterface.Timeout"

    // Events
    let MouseIsHeldDownTick: PropKey<CancelEventArgs<Terminal.Gui.Input.Mouse> -> unit> =
      PropKey.Create.event "IMouseHoldRepeaterInterface.MouseIsHeldDownTick_event"

  module internal IOrientationInterface =
    // Properties
    let Orientation: PropKey<Terminal.Gui.ViewBase.Orientation> =
      PropKey.Create.simple "IOrientationInterface.Orientation"

    // Events
    let OrientationChanged: PropKey<EventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "IOrientationInterface.OrientationChanged_event"

    let OrientationChanging: PropKey<CancelEventArgs<Terminal.Gui.ViewBase.Orientation> -> unit> =
      PropKey.Create.event "IOrientationInterface.OrientationChanging_event"

  module internal IValueInterface =
    // Properties
    let Value<'TValue> : PropKey<'TValue> =
      PropKey.Create.simple "IValueInterface.Value"

    // Events
    let ValueChangedUntyped: PropKey<ValueChangedEventArgs<System.Object> -> unit> =
      PropKey.Create.event "IValueInterface.ValueChangedUntyped_event"

    let ValueChanged<'TValue> : PropKey<ValueChangedEventArgs<'TValue> -> unit> =
      PropKey.Create.event "IValueInterface.ValueChanged_event"

    let ValueChanging<'TValue> : PropKey<ValueChangingEventArgs<'TValue> -> unit> =
      PropKey.Create.event "IValueInterface.ValueChanging_event"


  let View = ViewPKeys()
  let Adornment = AdornmentPKeys()
  let AttributePicker = AttributePickerPKeys()
  let Bar = BarPKeys()
  let Border = BorderPKeys()
  let Button = ButtonPKeys()
  let CharMap = CharMapPKeys()
  let CheckBox = CheckBoxPKeys()
  let ColorPicker = ColorPickerPKeys()
  let ColorPicker16 = ColorPicker16PKeys()
  let DatePicker = DatePickerPKeys()
  let FrameView = FrameViewPKeys()
  let GraphView = GraphViewPKeys()
  let HexView = HexViewPKeys()
  let Label = LabelPKeys()
  let LegendAnnotation = LegendAnnotationPKeys()
  let Line = LinePKeys()
  let LinearRange<'T> = LinearRangePKeys<'T>()
  let LinearRange' = LinearRangePKeys()
  let Link = LinkPKeys()
  let ListView = ListViewPKeys()
  let Margin = MarginPKeys()
  let Menu = MenuPKeys()
  let MenuBar = MenuBarPKeys()
  let NumericUpDown<'T> = NumericUpDownPKeys<'T>()
  let NumericUpDown' = NumericUpDownPKeys()
  let Padding = PaddingPKeys()
  let PopoverImpl = PopoverImplPKeys()

  let Popover<'TView, 'TResult when 'TView: (new: unit -> 'TView) and 'TView :> Terminal.Gui.ViewBase.View> =
    PopoverPKeys<'TView, 'TResult>()

  let PopoverMenu = PopoverMenuPKeys()
  let ProgressBar = ProgressBarPKeys()
  let Runnable = RunnablePKeys()
  let Runnable'<'TResult> = RunnablePKeys<'TResult>()
  let Dialog<'TResult> = DialogPKeys<'TResult>()
  let Dialog' = DialogPKeys()

  let Prompt<'TView, 'TResult when 'TView: (new: unit -> 'TView) and 'TView :> Terminal.Gui.ViewBase.View> =
    PromptPKeys<'TView, 'TResult>()

  let FileDialog = FileDialogPKeys()
  let OpenDialog = OpenDialogPKeys()
  let SaveDialog = SaveDialogPKeys()
  let ScrollBar = ScrollBarPKeys()
  let ScrollSlider = ScrollSliderPKeys()
  let SelectorBase = SelectorBasePKeys()
  let FlagSelector = FlagSelectorPKeys()
  let OptionSelector = OptionSelectorPKeys()

  let FlagSelector'<'TFlagsEnum
    when 'TFlagsEnum: struct
    and 'TFlagsEnum: (new: unit -> 'TFlagsEnum)
    and 'TFlagsEnum :> System.Enum
    and 'TFlagsEnum :> System.ValueType> =
    FlagSelectorPKeys<'TFlagsEnum>()

  let OptionSelector'<'TEnum
    when 'TEnum: struct and 'TEnum: (new: unit -> 'TEnum) and 'TEnum :> System.Enum and 'TEnum :> System.ValueType> =
    OptionSelectorPKeys<'TEnum>()

  let Shortcut = ShortcutPKeys()
  let MenuItem = MenuItemPKeys()
  let MenuBarItem = MenuBarItemPKeys()
  let SpinnerView = SpinnerViewPKeys()
  let StatusBar = StatusBarPKeys()
  let Tab = TabPKeys()
  let TabView = TabViewPKeys()
  let TableView = TableViewPKeys()
  let TextField = TextFieldPKeys()
  let DropDownList = DropDownListPKeys()
  let TextValidateField = TextValidateFieldPKeys()
  let DateEditor = DateEditorPKeys()
  let TextView = TextViewPKeys()
  let TimeEditor = TimeEditorPKeys()
  let TreeView<'T when 'T: not struct> = TreeViewPKeys<'T>()
  let TreeView' = TreeViewPKeys()
  let Window = WindowPKeys()
  let Wizard = WizardPKeys()
  let WizardStep = WizardStepPKeys()
