// This file is auto-generated by the Terminal.Gui.Elmish.Generator.
// Do not edit by hand.

namespace Terminal.Gui.Elmish

type IMenuItemTerminalElement =
  inherit ITerminalElement

type IMenuTerminalElement =
  inherit ITerminalElement

type IPopoverMenuTerminalElement =
  inherit ITerminalElement

type ITViewTerminalElement =
  inherit ITerminalElement

type ITabTerminalElement =
  inherit ITerminalElement

type IWizardStepTerminalElement =
  inherit ITerminalElement
