namespace Terminal.Gui.Elmish

type internal ViewType =
  | ``ViewBaseView``
  | ``ViewBaseAdornmentView``
  | ``ViewsAttributePicker``
  | ``ViewsBar``
  | ``ViewBaseBorderView``
  | ``ViewsButton``
  | ``ViewsCharMap``
  | ``ViewsCheckBox``
  | ``ViewsCode``
  | ``ViewsColorPicker``
  | ``ViewsColorPicker16``
  | ``ViewsDatePicker``
  | ``ViewsFrameView``
  | ``ViewsGraphView``
  | ``ViewsHexView``
  | ``ViewsImageView``
  | ``ViewsLabel``
  | ``ViewsLegendAnnotation``
  | ``ViewsLine``
  | ``LinearRangeViewBase<'TOption, 'TValue>``
  | ``LinearMultiSelector<'T>``
  | ``ViewsLinearMultiSelector``
  | ``LinearRange<'T>``
  | ``ViewsLinearRange``
  | ``LinearSelector<'T>``
  | ``ViewsLinearSelector``
  | ``ViewsLink``
  | ``ViewsListView``
  | ``ListView<'T>``
  | ``ViewBaseMarginView``
  | ``ViewsMarkdown``
  | ``ViewsMarkdownCodeBlock``
  | ``ViewsMarkdownTable``
  | ``ViewsMenu``
  | ``ViewsMenuBar``
  | ``NumericUpDown<'T>``
  | ``ViewsNumericUpDown``
  | ``ViewBasePaddingView``
  | ``AppPopoverImpl``
  | ``Popover<'TView, 'TResult>``
  | ``ViewsPopoverMenu``
  | ``ViewsProgressBar``
  | ``ViewsRunnable``
  | ``Runnable<'TResult>``
  | ``Dialog<'TResult>``
  | ``RunnableWrapper<'TView, 'TResult>``
  | ``ViewsDialog``
  | ``ViewsFileDialog``
  | ``Prompt<'TView, 'TResult>``
  | ``ViewsOpenDialog``
  | ``ViewsSaveDialog``
  | ``ViewsScrollBar``
  | ``ViewsScrollButton``
  | ``ViewsScrollSlider``
  | ``ViewsSelectorBase``
  | ``ViewsFlagSelector``
  | ``ViewsOptionSelector``
  | ``FlagSelector<'TFlagsEnum>``
  | ``OptionSelector<'TEnum>``
  | ``ViewsShortcut``
  | ``ViewsMenuItem``
  | ``ViewsMenuBarItem``
  | ``ViewsSpinnerView``
  | ``ViewsStatusBar``
  | ``ViewsTableView``
  | ``ViewsTabs``
  | ``ViewsTextField``
  | ``ViewsDropDownList``
  | ``DropDownList<'TEnum>``
  | ``ViewsTextValidateField``
  | ``ViewsDateEditor``
  | ``ViewsTextView``
  | ``ViewsTimeEditor``
  | ``ViewBaseTitleView``
  | ``ToolTipHost<'TView>``
  | ``TreeView<'T>``
  | ``ViewsTreeView``
  | ``ViewsWindow``
  | ``ViewsWizard``
  | ``ViewsWizardStep``
