namespace Terminal.Gui.Elmish

type ViewType =
  | ``ViewBaseView``
  | ``ViewBaseAdornment``
  | ``ViewsAttributePicker``
  | ``ViewsBar``
  | ``ViewBaseBorder``
  | ``ViewsButton``
  | ``ViewsCharMap``
  | ``ViewsCheckBox``
  | ``ViewsColorPicker``
  | ``ViewsColorPicker16``
  | ``ViewsDatePicker``
  | ``ViewsFrameView``
  | ``ViewsGraphView``
  | ``ViewsHexView``
  | ``ViewsLabel``
  | ``ViewsLegendAnnotation``
  | ``ViewsLine``
  | ``LinearRange<'T>``
  | ``ViewsLinearRange``
  | ``ViewsLink``
  | ``ViewsListView``
  | ``ViewBaseMargin``
  | ``ViewsMenu``
  | ``ViewsMenuBar``
  | ``NumericUpDown<'T>``
  | ``ViewsNumericUpDown``
  | ``ViewBasePadding``
  | ``AppPopoverImpl``
  | ``Popover<'TView, 'TResult>``
  | ``ViewsPopoverMenu``
  | ``ViewsProgressBar``
  | ``ViewsRunnable``
  | ``Runnable<'TResult>``
  | ``Dialog<'TResult>``
  | ``ViewsDialog``
  | ``Prompt<'TView, 'TResult>``
  | ``ViewsFileDialog``
  | ``ViewsOpenDialog``
  | ``ViewsSaveDialog``
  | ``ViewsScrollBar``
  | ``ViewsScrollSlider``
  | ``ViewsSelectorBase``
  | ``ViewsFlagSelector``
  | ``ViewsOptionSelector``
  | ``FlagSelector<'TFlagsEnum>``
  | ``OptionSelector<'TEnum>``
  | ``ViewsShortcut``
  | ``ViewsMenuItem``
  | ``ViewsMenuBarItem``
  | ``ViewsSpinnerView``
  | ``ViewsStatusBar``
  | ``ViewsTab``
  | ``ViewsTabView``
  | ``ViewsTableView``
  | ``ViewsTextField``
  | ``ViewsDropDownList``
  | ``ViewsTextValidateField``
  | ``ViewsDateEditor``
  | ``ViewsTextView``
  | ``ViewsTimeEditor``
  | ``TreeView<'T>``
  | ``ViewsTreeView``
  | ``ViewsWindow``
  | ``ViewsWizard``
  | ``ViewsWizardStep``
