name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Initial setup
        uses: ./.github/actions/initial-setup

      - name: Build main library
        run: dotnet build src/Terminal.Gui.Elmish/Terminal.Gui.Elmish.fsproj --no-restore

      - name: Build tests
        run: dotnet build src/Terminal.Gui.Elmish.Tests/Terminal.Gui.Elmish.Tests.fsproj --no-restore

      - name: Run tests
        run: dotnet test --project src/Terminal.Gui.Elmish.Tests/Terminal.Gui.Elmish.Tests.fsproj --no-build
        
      - name: Fantomas check
        run: ./fantomas-check.sh
